### ISSUE TITLE
Macro doesnt work on X4

### ISSUE THREAD

**Issue by Chris-dzgn** [cdrpro-macros/text-replacer#1]
Hi, i tried to use the macro textreplacer.gms on X4 but it doesnt show, i try loading it trough woxoom gmstools but doesnt work also, can you please fix it? I use X4 14.0.0.701, Thanks.

**Comment by SanichKotikov** [comment]
@christianalvites hi. That's because I've updated it for X7. Thanks to GIT you can download previous version https://github.com/cdrpro-macros/text-replacer/blob/000d3fcf3977894f5dfac86bb323bf2f93f1a6df/TextReplacer.gms

**Comment by Chris-dzgn** [comment]
Thank you very much, its working :)

2018-02-18 2:03 GMT-05:00 Sanich <notifications@github.com>:
